### ISSUE TITLE
Chat from in game does not appear in IRC

### ISSUE THREAD

**Issue by applesjgtl** [betterphp/SimpleIRC#1]
I've installed the plugin and configured it as such:
![Screen Shot 2012-12-11 at 7 54 53 PM](https://f.cloud.github.com/assets/2176220/7473/b3dfbeee-440f-11e2-9b1a-55bf28ccf584.png)

I've also added 'who' to commands.txt and a couple irc:minecraft entries in aliases.txt. This all seems to work fine, as when I send messages from my IRC client, they appear in minecraft as if sent from my minecraft username. Commands also work, as does log-in reports.

HOWEVER, if I send a message from within the game, while it appears in the game's chat, it will not show up in IRC. I'm currently using EssentialsChat, but no other chat plugins.

**Comment by betterphp** [comment]
Odd, it works on my server :P

Could you disabled EssentialsChat for a minute to make sure it's not that ? Then I can look into it if not.

**Comment by applesjgtl** [comment]
I disabled it, but it didn't solve my problem.

**Comment by betterphp** [comment]
Sorry for forgetting about this, could you try the new version and see if the problem still exists ?

**Comment by betterphp** [comment]
Assuming it was a bad chat plugin.

**Comment by applesjgtl** [comment]
Whoops, I don't think I ever replied to this. I'm trying the new version now. I'll send an update if it doesn't work within the next ten minutes. Otherwise, consider the problem solved.

**Comment by betterphp** [comment]
No problem. I've been running it for a while with no issues so I'm blaming a chat plugin that does bad things for the moment. :P
