### ISSUE TITLE
Stop IRC Pings

### ISSUE THREAD

**Issue by mrkirby153** [betterphp/SimpleIRC#2]
Every time i talk in irc, my IRC client pings me.
Ex: I say "Hi" ingame

and the bot says "(mrkirby153) hi" and i get pinged, is there a way to stop that?

**Comment by betterphp** [comment]
Good point, I don't have this problem as I use an alias. I can fix this though :D

**Comment by betterphp** [comment]
Fixed in the latest dev build :)
