### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by kohle** [betterphp/SimpleIRC#3]
Just simply doesn't work. I'm connecting to esper, I have the port, the bot name registered with NickServ, and everything else in the config is set up right. It just isn't relaying the chat back and forth.

**Comment by betterphp** [comment]
Version numbers for SimpleIRC and CraftBukkit please. Also a list of plugins you have installed, since some chat plugins do silly things that can break it (e.g. HeroChat).

**Comment by kohle** [comment]
Nevermind... it wasn't working for some reason. I just started the server back up and it's working perfectly.
