### ISSUE TITLE
Plugin inserts a ZeroWidthCharacter into usernames in IRC

### ISSUE THREAD

**Issue by MightyJoeYoung** [betterphp/SimpleIRC#4]
I don't know why the heck it does that, but it renders differently in different IRC clients. It's... pointless. I'd like it to stop :/

It sort of breaks some of my logs and bots too. Please address this issue.

Screenshot:
http://puu.sh/2mg6c

**Comment by betterphp** [comment]
That's the ping prevention feature, see https://github.com/betterphp/SimpleIRC/commit/300b3fb168d7fd7e1a9974af2a1fdf912ba336f8 There is an option to disable it in the config.
