### ISSUE TITLE
? in username from server.

### ISSUE THREAD

**Issue by OfficialHisha** [betterphp/SimpleIRC#5]
When I type from the server in-game the IRC always write a ? between the first and second letter like this: -botname- -s?ejemus- test or -botname- -a?ny-username- test
(<> instead of the --'s something wrong happend when I used the arrows..)

Running PEX for permissions, SimpleIRC and SimpleIRC formatter. Thanks in advise.

**Comment by OfficialHisha** [comment]
Read another ticket. Seems to be the anti ping feature. Could it be possible to customize the digt to whatever and define where it should be placed in the name?.

**Comment by betterphp** [comment]
The zero-width space _should_ be displayed correctly by modern clients/browsers configuration for the character used and it's location seems unnecessary.
